name: Run tests

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        payload:
          - { laravel: '9.*', php: '8.1', 'testbench': '7.*'}
          - { laravel: '9.*', php: '8.0', 'testbench': '7.*'}
          - { laravel: '8.*', php: '8.1', 'testbench': '6.*'}
          - { laravel: '8.*', php: '8.0', 'testbench': '6.*'}
          - { laravel: '8.*', php: '7.4', 'testbench': '6.*'}
          - { laravel: '7.*', php: '8.0', 'testbench': '5.*' }
          - { laravel: '7.*', php: '7.4', 'testbench': '5.*' }
          - { laravel: '6.*', php: '8.0', 'testbench': '4.*' }
          - { laravel: '6.*', php: '7.4', 'testbench': '4.*' }

    name: PHP ${{ matrix.payload.php }} - Laravel ${{ matrix.payload.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.payload.php }}
          extensions: mbstring, dom, fileinfo
          coverage: none

      - name: Execute checks
        run: |
          composer require "laravel/framework:${{ matrix.payload.laravel }}" "orchestra/testbench:${{ matrix.payload.testbench }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction --no-suggest
          vendor/bin/phpstan
